language: php

sudo: false

matrix:
  include:
    - php: 5.6

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer validate

install:
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit --configuration=phpunit.xml

notifications:
  email: false
